- name: "start mapred job history server for Hadoop older than 3.0"
  shell: "source ~/.bash_profile && ./mr-jobhistory-daemon.sh stop historyserver"
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  register: historyserver_stat
  changed_when: "'stopping historyserver' in historyserver_stat.stdout"
  when: hadoop_version is version('3.0.0','<')

- name: "stop mapred job history server for Hadoop newer than 3.0"
  shell: "source ~/.bash_profile && ./mapred --daemon stop historyserver"
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/bin"
  when: hadoop_version is version('3.0.0','>=')
