- name: "load job cache"
  shell: "source ~/.bash_profile && { ./check-job-cache.sh || ./load-job-cache.sh -allforce; }"
  args:
    executable: /bin/bash
    chdir: "{{ dw_ingest_home }}/bin/ingest"
  register: jobcache_stat
  changed_when: "'job cache dir' in jobcache_stat.stdout"
